import { initializeApp } from "https://www.gstatic.com/firebasejs/11.6.1/firebase-app.js";
import { getAuth, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, sendPasswordResetEmail } from "https://www.gstatic.com/firebasejs/11.6.1/firebase-auth.js";
import { getFirestore, doc, setDoc, onSnapshot } from "https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js";

// --- CONFIGURAÇÃO E VARIÁVEIS GLOBAIS ---
const firebaseConfig = typeof __firebase_config !== 'undefined' ? JSON.parse(__firebase_config) : { apiKey: "SUA_API_KEY", authDomain: "SEU_AUTH_DOMAIN", projectId: "SEU_PROJECT_ID" };
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
const auth = getAuth(app);
const appId = typeof __app_id !== 'undefined' ? __app_id : 'plano-de-estudos-ultra';

let userId = null;
let userProgress = {};
let dailyConfig = null;
let unsubscribeProgress = null;

const disciplinasData = {
    "Língua Portuguesa": { icon: "📚", color: "bg-blue-100", textColor: "text-blue-800", borderColor: "border-blue-400", topics: ["Interpretação de texto", "Ortografia oficial", "Acentuação gráfica", "Pontuação", "Classes de palavras", "Vozes verbais", "Concordância verbal e nominal", "Regência verbal e nominal", "Sintaxe: coordenação e subordinação", "Ocorrência de crase", "Sinônimos e antônimos", "Sentido próprio e figurado das palavras", "Reorganização de orações e períodos", "Redação (reconhecimento de frases corretas)"] },
    "Raciocínio Lógico, Mat. Financeira e Estatística": { icon: "🧠", color: "bg-indigo-100", textColor: "text-indigo-800", borderColor: "border-indigo-400", topics: ["Estrutura lógica de relações arbitrárias", "Compreensão da lógica de situações", "Compreensão do processo lógico e conclusões", "Juros simples (Montante, Taxas, Capitais)", "Juros compostos (Montante, Taxas, Capitais)", "Descontos: simples e composto", "Sistemas de Amortização (Francês, SAC, Misto)", "Fluxo de caixa (Valor atual, TIR)", "Estatística descritiva e análise exploratória", "Probabilidade (Definições, Condicional)", "Variáveis aleatórias e distribuições", "Esperança e variância de variável aleatória", "Distribuições conjuntas, covariância, correlação", "Noção de amostra aleatória e distribuição", "Noções de estimação pontual e intervalar", "Noções de teste de hipótese (nível de significância)"] },
    "Direito Constitucional": { icon: "⚖️", color: "bg-red-100", textColor: "text-red-800", borderColor: "border-red-400", topics: ["Constituição da República de 1988", "Aplicabilidade das normas constitucionais", "Direitos e garantias fundamentais", "Organização político-administrativa do Estado", "Administração Pública (Disposições gerais)", "Poder Executivo (Atribuições do Presidente)", "Poder Legislativo (Estrutura, Processo)", "Fiscalização contábil, financeira e orçamentária", "Poder Judiciário (Disposições gerais)", "Funções essenciais à Justiça (MP, Advocacia)", "Controle de constitucionalidade (Judicial e não judicial)", "Súmula vinculante e Reclamação", "Ordem econômica e financeira", "Constituição do Estado de Goiás (Poderes, Ordem Econômica)"] },
    "Direito Administrativo": { icon: "🏛️", color: "bg-orange-100", textColor: "text-orange-800", borderColor: "border-orange-400", topics: ["Estado, Governo e Administração Pública", "Direito Administrativo (Conceito, Objeto, Fontes)", "Ato administrativo (Requisitos, Atributos, Extinção)", "Agentes públicos (Disposições constitucionais)", "Estatuto dos servidores de GO (Lei 20.756/20)", "Carreira do fisco de GO (Lei 13.266/98)", "Poderes da Administração Pública", "Regime jurídico-administrativo (Princípios)", "Responsabilidade civil do Estado", "Serviços Públicos (Concessão, Permissão)", "Organização Administrativa (Direta e Indireta)", "Controle da Administração Pública", "Improbidade administrativa (Lei 8.429/92 com alt.)", "Lei Anticorrupção (Lei 12.846/2013)", "Licitações e Contratos (Lei 14.133/2021)", "Bens Públicos (Regime jurídico, Classificação)", "Lei de acesso à informação (Lei 12.527/2011)", "Lei Geral de Proteção de Dados (Lei 13.709/2018)"] },
    "Direito Financeiro": { icon: "💰", color: "bg-amber-100", textColor: "text-amber-800", borderColor: "border-amber-400", topics: ["Orçamento na CF/88 (PPA, LDO, LOA)", "Créditos Adicionais e Emendas parlamentares", "Lei de Responsabilidade Fiscal (LC 101/2000)", "Normas Gerais de Direito Financeiro (Lei 4.320/1964)"] },
    "Direito Civil, Penal e Empresarial": { icon: "🤝", color: "bg-yellow-100", textColor: "text-yellow-800", borderColor: "border-yellow-400", topics: ["LINDB", "Pessoas naturais (Personalidade, Capacidade)", "Pessoas jurídicas (Associações, Fundações)", "Bens (Imóveis, Móveis, Públicos)", "Fato e Negócio jurídico (Invalidade)", "Prescrição e Decadência", "Obrigações (Adimplemento, Inadimplemento)", "Contratos (Princípios, Disposições gerais)", "Responsabilidade civil (Objetiva e Subjetiva)", "Aplicação da lei penal (Tempo e Espaço)", "Teoria do Crime (Causalidade, Tipicidade, Culpabilidade)", "Crimes contra a Fé Pública", "Crimes contra a Administração Pública", "Crimes contra a ordem tributária (Lei 8.137/90)", "Abuso de autoridade (Lei 13.869/2019)", "Direito empresarial (Teoria da empresa)", "Registro de empresa e Empresário irregular", "Direito societário (Sociedade simples e empresária)", "Sociedade limitada e Sociedade anônima", "Operações societárias (Fusão, Cisão, Incorporação)", "Falência e recuperação judicial e extrajudicial"] },
    "Economia": { icon: "📈", color: "bg-lime-100", textColor: "text-lime-800", borderColor: "border-lime-400", topics: ["Conceitos fundamentais de economia", "Teoria elementar de equilíbrio do mercado", "Fatores de oferta e procura", "Efeitos de deslocamentos das curvas", "Elasticidades-preço da procura e da oferta", "Equilíbrio da firma em diferentes mercados", "A necessidade econômica da tributação", "Classificação dos impostos", "Tributação e eficiência (Peso Morto)", "Tributação Ótima (Regra de Ramsey)", "Curva de Laffer", "Tributação e equidade (Trade-off)", "Incidência econômica dos tributos", "Tributação em concorrência perfeita e monopólio", "Política tributária e decisões de consumo", "Macroeconomia: Fluxo Circular da Renda", "Agregados macroeconômicos (PIB, Consumo)", "Determinação do produto de equilíbrio (Curva IS)", "Política monetária (Curva LM)", "PIB real vs. PIB nominal", "Inflação: conceitos e mensuração", "Contas nacionais do Brasil", "Balanço de Pagamentos", "Noções sobre economia do setor público", "Políticas fiscal, monetária e cambial", "Efeitos da atuação do Estado na economia", "Sistema Tributário como instrumento de distribuição"] },
    "Contabilidade Geral": { icon: "🧾", color: "bg-green-100", textColor: "text-green-800", borderColor: "border-green-400", topics: ["Conceito, objeto e objetivos da Contabilidade", "Princípios e Normas Brasileiras de Contabilidade", "Itens patrimoniais: Ativo, Passivo e PL", "Classificação e avaliação de itens patrimoniais", "Regime de Competência e Apuração do resultado", "Estoques: Tipos, Critérios e Métodos de avaliação", "Ativo Imobilizado: Mensuração e Depreciação", "Ativo Intangível: Mensuração e Amortização", "Redução ao valor recuperável (Impairment)", "Estimativa de perdas e Provisões (Contingências)", "Balanço Patrimonial (Estrutura)", "Demonstração do Resultado do Exercício (DRE)", "DMPL e DLPA"] },
    "Realidade de Goiás": { icon: "🗺️", color: "bg-emerald-100", textColor: "text-emerald-800", borderColor: "border-emerald-400", topics: ["Formação econômica de Goiás (mineração, agropecuária)", "Modernização da economia goiana (Estrada de Ferro, Goiânia, Brasília)", "Modernização da agricultura e urbanização", "População goiana: movimentos migratórios", "Economia goiana: industrialização e infraestrutura", "Regiões goianas e desigualdades regionais", "Aspectos físicos do território goiano", "História política de Goiás", "História social de Goiás", "Atualidades econômicas, políticas e sociais"] },
    "Tecnologias da Informação": { icon: "💻", color: "bg-teal-100", textColor: "text-teal-800", borderColor: "border-teal-400", topics: ["Fundamentos de Banco de Dados (SQL, T-SQL, PL/SQL)", "Modelagem de dados: relacional e multidimensional", "Administração de banco de dados relacionais", "Pipeline de Dados (ETL, ELT)", "OLAP: Conceitos e aplicações", "Modelagem e Otimização de Bases Multidimensionais", "Pré-processamento de Dados", "Data Lake: Conceito e aplicações", "Data Mining e Data Warehouse", "Big Data: Conceitos e premissas", "Bancos de Dados Não Relacionais (NoSQL)", "Gerenciamento de Projetos (PMBOK 7ª edição)", "Metodologias Ágeis (Scrum, Kanban, Lean, XP)", "Análise de Agrupamentos (Clusterização)", "Análise Fatorial por Componentes Principais", "Análise de Correspondência (Simples e Múltipla)", "Modelos Lineares de Regressão", "Modelos de Regressão Logística", "Modelos de Regressão para Dados de Contagem", "Redes Neurais Artificiais e Machine Learning", "Visualização e Análise Exploratória de Dados", "Business Intelligence ( dashboards, Power BI)", "Séries Temporais (Sazonalidade, Tendência, ARIMA)"] },
    "Auditoria": { icon: "🔍", color: "bg-cyan-100", textColor: "text-cyan-800", borderColor: "border-cyan-400", topics: ["Planejamento de Auditoria", "Amostragem em Auditoria", "Testes de observância (ou de controles)", "Testes substantivos", "Testes para subavaliação e superavaliação", "Evidências de auditoria e Procedimentos", "Identificação de fraudes na escrita contábil", "Auditoria no ativo circulante", "Recomposição contábil do fluxo de caixa", "Auditoria nas contas de resultado", "Irregularidades (Ocultação de ativos, Saldo credor de caixa)", "Suprimento de caixa sem comprovação", "Aquisições não contabilizadas", "Falta de registro de passivos", "Superavaliação de custos", "Estrutura da EFD ICMS/IPI e XML da NF-e", "Relacionamento entre registros (EFD e NF-e)", "Normas Brasileiras de Auditoria (NBC TA e NBC PA)"] },
    "Contabilidade Avançada e de Custos": { icon: "📊", color: "bg-sky-100", textColor: "text-sky-800", borderColor: "border-sky-400", topics: ["Políticas Contábeis, Mudança de Estimativa e Retificação de Erro", "Mensuração a Valor Justo", "Ajuste a Valor Presente", "Instrumentos financeiros", "Propriedade para Investimento", "Operações de arrendamento mercantil", "Participações Societárias (Coligadas, Controladas, MEP)", "Reorganização de empresas (Incorporação, fusão, cisão)", "Mais valia, Goodwill e Deságio", "Subvenção e Assistência governamentais", "Conversão de demonstrações contábeis (Câmbio)", "Demonstração dos Fluxos de Caixa (DFC)", "Demonstração do Valor Adicionado (DVA)", "Conceitos e terminologia de Custos", "Classificação e apropriação dos custos", "Departamentalização", "Sistemas de Custeio (Absorção, Variável, ABC)", "Produção (Ordem, Contínua, Conjunta)", "Custos Estimados e Custo Padrão", "Análise Custo x Volume x Lucro (Ponto de Equilíbrio)", "Margem de Contribuição e Alavancagem Operacional"] },
    "Direito Tributário I": { icon: "⚖️", color: "bg-purple-100", textColor: "text-purple-800", borderColor: "border-purple-400", topics: ["Sistema Tributário Nacional na CF", "Princípios constitucionais tributários", "Espécies tributárias", "Limitações ao Poder de Tributar (Imunidades)", "Impostos da União", "Impostos dos Estados e DF", "Impostos dos Municípios", "Repartição das Receitas Tributárias", "CTN: Competência e Legislação Tributária", "Obrigação Tributária: Fato Gerador e Sujeitos", "Responsabilidade Tributária (Sucessores, Terceiros)", "Crédito Tributário: Lançamento", "Suspensão da exigibilidade do Crédito", "Extinção do Crédito Tributário", "Exclusão do Crédito (Isenção, Anistia)", "Garantias e Privilégios do Crédito", "Administração Tributária (Fiscalização, Dívida Ativa)", "LC 24/1975 (Convênios ICMS)", "LC 87/1996 (Lei Kandir)", "LC 105/2001 (Sigilo Bancário)", "LC 116/2003 (ISS)", "LC 123/2006 (Simples Nacional)", "LC 192/2022 (ICMS Combustíveis)", "Súmulas Vinculantes do STF em matéria tributária"] },
    "Direito Tributário II - Reforma Tributária": { icon: "📜", color: "bg-fuchsia-100", textColor: "text-fuchsia-800", borderColor: "border-fuchsia-400", topics: ["EC 132/2023 - Visão Geral", "LC 214/2025: Normas Gerais do IBS e da CBS", "Fato Gerador, Base de Cálculo e Alíquotas IBS/CBS", "Não cumulatividade e sistema de créditos", "Operacionalização (Split Payment)", "IBS/CBS sobre Importações e Exportações", "Desoneração da aquisição de bens de capital", "Devolução Personalizada (Cashback)", "Cesta Básica Nacional de Alimentos", "Regimes Diferenciados (Reduções 30%, 60%, Isenção)", "Regimes Diferenciados (Produtor Rural, Transportador)", "Regimes Específicos: Combustíveis", "Regimes Específicos: Serviços Financeiros e Planos de Saúde", "Regimes Específicos: Bens Imóveis e Cooperativas", "Administração do IBS e Comitê Gestor"] },
    "Legislação Tributária Estadual": { icon: "🇬🇴", color: "bg-pink-100", textColor: "text-pink-800", borderColor: "border-pink-400", topics: ["Código Tributário de Goiás (Lei 11.651/91)", "Regulamento do CTE (Decreto 4.852/97)", "Processo Administrativo Tributário (Lei 16.469/09)", "Substituição Tributária (Anexo VIII do RCTE)", "Benefícios Fiscais (Anexo IX do RCTE)", "Obrigações Acessórias (Anexo XII do RCTE)", "DIFAL a não contribuinte (Anexo XV do RCTE)", "Informações de Meios de Pagamento (Anexo XVIII)", "Ajuste SINIEF 07/05 (NF-e)", "Ajuste SINIEF 19/16 (NFC-e)", "Ajuste SINIEF 21/10 (MDF-e)", "ProGoiás (Lei 20.787/2020)", "FUNDEINFRA (Lei 21.670/22)", "Autorregularização (IN 199/2022-SRE)", "Código de Direitos do Contribuinte (LC 104/13)", "FOMENTAR (Lei 9.489/84)", "Alterações FOMENTAR (Lei 11.180/90)", "PRODUZIR e FUNPRODUZIR (Lei 13.591/2000)"] }
};

const authModal = document.getElementById('authModal');
const authContent = document.getElementById('authContent');
const configModal = document.getElementById('configModal');
const mainApp = document.getElementById('mainApp');
const authFeedback = document.getElementById('auth-feedback');

// --- AUTENTICAÇÃO E DADOS ---

onAuthStateChanged(auth, (user) => {
    if (user) {
        userId = user.uid;
        document.getElementById('user-email').textContent = user.email;
        document.getElementById('user-email').classList.remove('hidden');
        hideAuthModal();
        loadAndListenForProgress(userId);
    } else {
        userId = null;
        if(unsubscribeProgress) unsubscribeProgress();
        userProgress = {};
        dailyConfig = null;
        mainApp.classList.add('hidden');
        document.getElementById('user-email').classList.add('hidden');
        showAuthModal();
    }
});

const loadAndListenForProgress = (uid) => {
    if (!uid) return;
    if (unsubscribeProgress) unsubscribeProgress();
    const progressRef = doc(db, 'artifacts', appId, 'users', uid);
    unsubscribeProgress = onSnapshot(progressRef, async (docSnap) => {
        if (docSnap.exists() && docSnap.data().progress) {
            userProgress = docSnap.data().progress;
        } else {
            const initialProgress = {};
            Object.keys(disciplinasData).forEach(d => initialProgress[d] = 0);
            await setDoc(progressRef, { progress: initialProgress });
            userProgress = initialProgress;
        }
        renderGeneralProgress();
        initializeAppState();
    }, error => console.error("Erro ao ouvir progresso:", error));
};

const saveProgress = async (newProgress) => {
    if (!userId) return;
    const progressRef = doc(db, 'artifacts', appId, 'users', userId);
    try { await setDoc(progressRef, { progress: newProgress }, { merge: true }); }
    catch (error) { console.error("Erro ao salvar progresso:", error); }
};

// --- ESTADO DA APLICAÇÃO E UI ---

const initializeAppState = () => { loadDailyConfig(); if (dailyConfig && dailyConfig.plan) { showMainApp(); } else { showConfigModal(); } };
const showAuthModal = () => { switchAuthForm('login-form'); authModal.classList.remove('hidden'); authModal.classList.add('flex'); setTimeout(() => authContent.classList.remove('scale-95', 'opacity-0'), 50); };
const hideAuthModal = () => { authContent.classList.add('scale-95', 'opacity-0'); setTimeout(() => { authModal.classList.add('hidden'); authModal.classList.remove('flex'); }, 200); };
const showConfigModal = () => { setupModal(); mainApp.classList.add('hidden'); configModal.classList.remove('hidden'); configModal.classList.add('flex'); setTimeout(() => document.getElementById('modalContent').classList.remove('scale-95', 'opacity-0'), 50); };
const hideConfigModal = () => { const modalContent = document.getElementById('modalContent'); modalContent.classList.add('scale-95', 'opacity-0'); setTimeout(() => { configModal.classList.add('hidden'); configModal.classList.remove('flex'); }, 200); };
const setupModal = () => { const now = new Date(); const hour = now.getHours(); let greetingText = (hour < 12) ? "Bom dia" : (hour < 18) ? "Boa tarde" : "Boa noite"; document.getElementById('greeting').innerHTML = `${greetingText}, futuro(a) Auditor(a)!`; document.getElementById('currentDate').textContent = `Hoje é ${now.toLocaleDateString('pt-BR', { day: '2-digit', month: 'long', year: 'numeric' })}`; const postos = ['02', '03', '04', '06', '07', '08', '09']; document.getElementById('postosGrid').innerHTML = postos.map(p => `<div class="custom-checkbox"><input type="checkbox" id="posto-${p}" name="posto" value="${p}" class="posto-checkbox"><label for="posto-${p}" class="block p-2 sm:p-3 rounded-lg cursor-pointer font-bold text-base sm:text-lg">${p}</label></div>`).join(''); document.querySelectorAll('input[name="turno"], .posto-checkbox, #desativar3e4').forEach(el => el.addEventListener('change', validateConfig)); document.getElementById('desativar3e4').addEventListener('change', e => { const checked = e.target.checked; document.getElementById('posto-03').checked = checked; document.getElementById('posto-04').checked = checked; validateConfig(); }); document.getElementById('iniciarEstudosBtn').onclick = handleStartStudies; };
const validateConfig = () => { const turnoSelecionado = document.querySelector('input[name="turno"]:checked'); const postosSelecionados = document.querySelectorAll('.posto-checkbox:checked').length; document.getElementById('iniciarEstudosBtn').disabled = !(turnoSelecionado && postosSelecionados > 0); };
const handleStartStudies = () => { const turno = document.querySelector('input[name="turno"]:checked').value; const postosAtivos = Array.from(document.querySelectorAll('.posto-checkbox:checked')).map(cb => cb.value); const plan = generateStudyPlan(turno, postosAtivos); dailyConfig = { date: new Date().toLocaleDateString('pt-BR'), turno, postosAtivos, plan }; localStorage.setItem(`dailyConfig_${userId}`, JSON.stringify(dailyConfig)); showMainApp(); };
const loadDailyConfig = () => { if(!userId) return; const savedConfig = localStorage.getItem(`dailyConfig_${userId}`); if (savedConfig) { const parsedConfig = JSON.parse(savedConfig); if (parsedConfig.date === new Date().toLocaleDateString('pt-BR')) { dailyConfig = parsedConfig; } else { localStorage.removeItem(`dailyConfig_${userId}`); dailyConfig = null; } } };
const showMainApp = () => { hideConfigModal(); renderStudySessions(dailyConfig.plan); mainApp.classList.remove('hidden'); document.getElementById('headerDate').textContent = new Date().toLocaleDateString('pt-BR', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }); };

// --- RENDERIZAÇÃO E LÓGICA DE ESTUDO ---
const generateStudyPlan = (turno, postosAtivos) => { const horarios = []; let startHour = turno === 'primeiro' ? 8 : 11; for (let i = 0; i < postosAtivos.length; i++) { const endHour = (startHour + 3) % 24; horarios.push(`${String(startHour).padStart(2, '0')}:00 - ${String(endHour).padStart(2, '0')}:00`); startHour = (endHour + 3) % 24; } let plan = []; let tempProgress = { ...userProgress }; for (let i = 0; i < postosAtivos.length; i++) { let availableDisciplines = Object.keys(disciplinasData).filter(name => (tempProgress[name] || 0) < disciplinasData[name].topics.length).map(name => ({ name, progress: tempProgress[name] || 0 })).sort((a, b) => a.progress - b.progress || Math.random() - 0.5); if (availableDisciplines.length === 0) break; const disciplinaName = availableDisciplines[0].name; const disciplina = disciplinasData[disciplinaName]; const currentTopicIndex = tempProgress[disciplinaName] || 0; const topicText = `${currentTopicIndex + 1}. ${disciplina.topics[currentTopicIndex]}`; plan.push({ posto: postosAtivos[i], horario: horarios[i], disciplina: disciplinaName, topico: topicText, topicIndex: currentTopicIndex, ...disciplinasData[disciplinaName] }); tempProgress[disciplinaName] = currentTopicIndex + 1; } return plan; };
const renderStudySessions = (plan) => { const sessoesContainer = document.getElementById('sessoesContainer'); if (!plan || plan.length === 0) { sessoesContainer.innerHTML = `<div class="bg-white/70 backdrop-blur-sm p-6 rounded-lg shadow-md text-center text-gray-500"><p>Nenhuma sessão de estudo para hoje. Configure seu dia ou parabéns por ter concluído tudo!</p></div>`; return; } sessoesContainer.innerHTML = plan.map((sessao) => { const isCompleted = userProgress[sessao.disciplina] > sessao.topicIndex; const completedClass = isCompleted ? 'session-completed' : ''; const buttonHtml = isCompleted ? `<div class="flex items-center justify-end gap-2"><span class="text-green-500 font-bold flex items-center gap-1">✔️ Concluído</span><button class="undo-btn bg-gray-400 text-white px-3 py-1 text-xs rounded-md hover:bg-gray-500 transition-all" data-disciplina="${sessao.disciplina}" data-topic-index="${sessao.topicIndex}">Desfazer</button></div>` : `<button class="complete-btn bg-green-500 text-white px-3 py-1 text-sm rounded-md hover:bg-green-600 transition-all" data-disciplina="${sessao.disciplina}" data-topic-index="${sessao.topicIndex}">Concluir Tópico</button>`; return `<div class="sessao-card border-l-4 p-4 rounded-r-lg shadow-lg transition-all ${sessao.color} ${sessao.borderColor} ${completedClass}"><div class="flex items-start space-x-3 sm:space-x-4"><div class="text-2xl pt-1">${sessao.icon}</div><div class="flex-1"><div class="flex flex-wrap items-center justify-between gap-2"><span class="font-bold ${sessao.textColor} text-base sm:text-lg">${sessao.disciplina}</span><span class="text-xs sm:text-sm font-semibold bg-white/60 px-2 py-1 rounded-full whitespace-nowrap text-gray-700">Posto ${sessao.posto} | ${sessao.horario}</span></div><p class="mt-1 text-gray-600 text-sm sm:text-base">${sessao.topico}</p><div class="mt-3 text-right"> ${buttonHtml} </div></div></div></div>`; }).join(''); highlightCurrentSession(); };
const handleCompleteTopic = (e) => { const { disciplina, topicIndex } = e.target.dataset; const topicIndexInt = parseInt(topicIndex, 10); if (userProgress[disciplina] === topicIndexInt) { const newProgress = { ...userProgress }; newProgress[disciplina]++; saveProgress(newProgress); } };
const handleUndoTopic = (e) => { const { disciplina, topicIndex } = e.target.dataset; const topicIndexInt = parseInt(topicIndex, 10); if (userProgress[disciplina] === topicIndexInt + 1) { const newProgress = { ...userProgress }; newProgress[disciplina]--; saveProgress(newProgress); }};
const highlightCurrentSession = () => { document.querySelectorAll('.current-session-highlight').forEach(el => el.classList.remove('current-session-highlight')); const now = new Date(); const currentTime = now.getHours() * 60 + now.getMinutes(); let nextSessionEl = null; let foundCurrent = false; if (dailyConfig && dailyConfig.plan) { for (const sessao of dailyConfig.plan) { const [start] = sessao.horario.split(' - '); const [startHour] = start.split(':').map(Number); const sessionStart = startHour * 60; const sessionEnd = sessionStart + (3 * 60); const sessionEl = Array.from(document.querySelectorAll('.sessao-card')).find(el => el.querySelector('p').textContent.includes(sessao.topico)); if (!sessionEl) continue; if (currentTime >= sessionStart && currentTime < sessionEnd) { sessionEl.classList.add('current-session-highlight'); sessionEl.scrollIntoView({ behavior: 'smooth', block: 'center' }); foundCurrent = true; break; } else if (currentTime < sessionStart && !nextSessionEl) { nextSessionEl = sessionEl; } } if (!foundCurrent && nextSessionEl) { nextSessionEl.classList.add('current-session-highlight'); nextSessionEl.scrollIntoView({ behavior: 'smooth', block: 'center' }); } } setTimeout(highlightCurrentSession, 60000); };
const renderGeneralProgress = () => { const container = document.getElementById('progressoContainer'); let totalTopics = 0; let completedTopics = 0; const disciplinesHTML = Object.entries(disciplinasData).map(([name, data]) => { const total = data.topics.length; const completed = userProgress[name] || 0; const percentage = total > 0 ? Math.round((completed / total) * 100) : 0; totalTopics += total; completedTopics += completed; return `<div class="accordion-item bg-white/70 backdrop-blur-sm rounded-lg shadow-md overflow-hidden"><div class="accordion-header flex justify-between items-center p-3 cursor-pointer" data-target="#content-${name.replace(/[^a-zA-Z0-9]/g, '')}"><div class="flex items-center space-x-3"><span class="text-lg">${data.icon}</span><span class="font-semibold text-sm text-slate-700 flex-1">${name}</span></div><div class="flex items-center space-x-2"><span class="text-xs font-bold ${data.textColor}">${percentage}%</span><svg class="arrow-icon h-5 w-5 text-slate-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" /></svg></div></div><div class="progress-bar h-1.5 ${data.color} w-full"><div class="progress-bar-inner h-full ${data.color.replace('100', '500')}" style="width: ${percentage}%;"></div></div><div id="content-${name.replace(/[^a-zA-Z0-9]/g, '')}" class="accordion-content"><ul class="text-xs text-slate-600 space-y-1 py-2">${data.topics.map((topic, index) => `<li class="flex items-start gap-2 ${index < completed ? 'line-through text-slate-400' : ''}"><span class="mt-0.5">${index < completed ? '✅' : '▪️'}</span><span>${index + 1}. ${topic}</span></li>`).join('')}</ul></div></div>`; }).join(''); const totalPercentage = totalTopics > 0 ? Math.round((completedTopics / totalTopics) * 100) : 0; const summaryHTML = `<div class="bg-gradient-to-br from-sky-500 to-blue-600 text-white p-6 rounded-xl shadow-xl text-center"><h3 class="text-lg font-bold">Progresso Total</h3><div class="text-5xl font-extrabold my-2">${totalPercentage}%</div><p class="text-sm opacity-90">${completedTopics} de ${totalTopics} tópicos concluídos.</p></div>`; container.innerHTML = summaryHTML + disciplinesHTML; };

// --- LÓGICA DE AUTENTICAÇÃO ---
const setFeedback = (message, type) => { authFeedback.textContent = message; authFeedback.className = `text-sm mt-4 h-4 ${type === 'error' ? 'text-red-500' : 'text-green-500'}`; };
const handleLogin = () => { const email = document.getElementById('login-email').value; const password = document.getElementById('login-password').value; setFeedback('Entrando...', 'info'); signInWithEmailAndPassword(auth, email, password).catch(error => setFeedback(error.code === 'auth/invalid-credential' ? 'E-mail ou senha inválidos.' : 'Erro ao fazer login.', 'error')); };
const handleSignup = () => { const email = document.getElementById('signup-email').value; const password = document.getElementById('signup-password').value; if(password.length < 6) { setFeedback('A senha deve ter no mínimo 6 caracteres.', 'error'); return; } setFeedback('Criando conta...', 'info'); createUserWithEmailAndPassword(auth, email, password).catch(error => setFeedback(error.code === 'auth/email-already-in-use' ? 'Este e-mail já está em uso.' : 'Erro ao criar conta.', 'error')); };
const handlePasswordReset = () => { const email = document.getElementById('reset-email').value; if(!email) { setFeedback('Por favor, insira seu e-mail.', 'error'); return; } setFeedback('Enviando e-mail...', 'info'); sendPasswordResetEmail(auth, email).then(() => setFeedback('E-mail de recuperação enviado!', 'success')).catch(error => setFeedback('Erro ao enviar e-mail.', 'error')); };
const handleLogout = () => { signOut(auth).catch(error => console.error("Erro ao sair:", error)); };
const switchAuthForm = (formId) => { document.querySelectorAll('.auth-form').forEach(form => form.classList.remove('active')); document.getElementById(formId).classList.add('active'); setFeedback('', 'info'); };
const togglePasswordVisibility = (btn) => { const input = btn.previousElementSibling; const eyeOpen = btn.querySelector('.eye-open'); const eyeClosed = btn.querySelector('.eye-closed'); if(input.type === 'password') { input.type = 'text'; eyeOpen.classList.add('hidden'); eyeClosed.classList.remove('hidden'); } else { input.type = 'password'; eyeOpen.classList.remove('hidden'); eyeClosed.classList.add('hidden'); } };

// --- EVENT LISTENERS ---
document.addEventListener('DOMContentLoaded', () => {
    // Troca de formulário de autenticação
    document.getElementById('show-signup').addEventListener('click', (e) => { e.preventDefault(); switchAuthForm('signup-form'); });
    document.getElementById('show-login-from-signup').addEventListener('click', (e) => { e.preventDefault(); switchAuthForm('login-form'); });
    document.getElementById('show-forgot-password').addEventListener('click', (e) => { e.preventDefault(); switchAuthForm('forgot-password-form'); });
    document.getElementById('back-to-login').addEventListener('click', (e) => { e.preventDefault(); switchAuthForm('login-form'); });

    // Ações de autenticação
    document.getElementById('login-btn').addEventListener('click', handleLogin);
    document.getElementById('signup-btn').addEventListener('click', handleSignup);
    document.getElementById('reset-password-btn').addEventListener('click', handlePasswordReset);
    document.getElementById('logout-btn').addEventListener('click', handleLogout);

    // Alternar visibilidade da senha
    document.querySelectorAll('.toggle-password').forEach(btn => btn.addEventListener('click', () => togglePasswordVisibility(btn)));
    
    // Ações do aplicativo
    document.getElementById('reconfigurarDiaBtn').addEventListener('click', () => { localStorage.removeItem(`dailyConfig_${userId}`); dailyConfig = null; showConfigModal(); });
    document.getElementById('sessoesContainer').addEventListener('click', (e) => { if (e.target.classList.contains('complete-btn')) handleCompleteTopic(e); else if (e.target.classList.contains('undo-btn')) handleUndoTopic(e); });
    document.getElementById('progressoContainer').addEventListener('click', (e) => {
        const header = e.target.closest('.accordion-header');
        if (header) {
            const content = document.querySelector(header.dataset.target);
            if (content) {
                header.classList.toggle('open');
                content.classList.toggle('open');
            }
        }
    });
});

